from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class WriteVersionHook(BuildHookInterface):
    def initialize(self, version, build_data):
        # This method runs BEFORE the wheel/sdist build starts.
        # 'version' is already resolved by hatch, from package.json via hatch-nodejs-version.

        out_path = self.root / "bqscales" / "_version.py"

        out_path.write_text(
            f"# Auto-generated by Hatch build hook\n__version__ = \"{version}\"\n"
        )
